export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  name: string;
  icon: string;
  emojis: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & Mensen',
    icon: '😀',
    emojis: [
      { emoji: '😀', name: 'smile', keywords: ['happy', 'smile', 'blij', ':D', ':-D'] },
      { emoji: '😃', name: 'smiley', keywords: ['happy', 'smile', 'blij'] },
      { emoji: '😄', name: 'smile_grin', keywords: ['happy', 'smile', 'blij'] },
      { emoji: '😁', name: 'grin', keywords: ['happy', 'smile', 'blij'] },
      { emoji: '😆', name: 'laughing', keywords: ['happy', 'laugh', 'lachen', 'XD', 'xD', 'xd'] },
      { emoji: '😅', name: 'sweat_smile', keywords: ['happy', 'laugh', 'lachen', 'stress'] },
      { emoji: '🤣', name: 'rofl', keywords: ['rolling', 'lachen'] },
      { emoji: '😂', name: 'joy', keywords: ['laugh', 'lachen', 'huilen'] },
      { emoji: '😊', name: 'blush', keywords: ['smile', 'blij'] },
      { emoji: '😇', name: 'halo', keywords: ['engel'] },
      { emoji: '🙂', name: 'slight_smile', keywords: ['smile', 'blij', ':)', ':-)'] },
      { emoji: '🙃', name: 'upside_down', keywords: ['gek'] },
      { emoji: '😉', name: 'wink', keywords: ['wink', 'knipoog', ';)', ';-)'] },
      { emoji: '😌', name: 'relieved', keywords: ['fijn'] },
      { emoji: '😍', name: 'heart_eyes', keywords: ['love', 'verliefd'] },
      { emoji: '🥰', name: 'smiling_face_with_hearts', keywords: ['love', 'verliefd'] },
      { emoji: '😘', name: 'kissing_heart', keywords: ['kiss', 'kus', ':*', ':-*'] },
      { emoji: '😗', name: 'kissing', keywords: ['kiss'] },
      { emoji: '😙', name: 'kissing_smiling_eyes', keywords: ['kiss'] },
      { emoji: '😚', name: 'kissing_closed_eyes', keywords: ['kiss'] },
      { emoji: '😋', name: 'yum', keywords: ['lekker', 'honger'] },
      { emoji: '😛', name: 'stuck_out_tongue', keywords: ['tongue', 'tong', ':P', ':p', ':-P', ':-p'] },
      { emoji: '😜', name: 'stuck_out_tongue_winking_eye', keywords: ['wink', 'tongue', 'gekkie'] },
      { emoji: '🤪', name: 'zany_face', keywords: ['gek'] },
      { emoji: '😝', name: 'stuck_out_tongue_closed_eyes', keywords: ['laugh'] },
      { emoji: '🤑', name: 'money_mouth', keywords: ['geld'] },
      { emoji: '🤗', name: 'hugging', keywords: ['knuffel'] },
      { emoji: '🤭', name: 'hand_over_mouth', keywords: ['oeps'] },
      { emoji: '🥱', name: 'yawning_face', keywords: ['gaap'] },
      { emoji: '😴', name: 'sleeping', keywords: ['slaap'] },
      { emoji: '😌', name: 'relieved', keywords: ['fijn'] },
      { emoji: '😎', name: 'sunglasses', keywords: ['cool', 'stoer', 'B)', 'B-)'] },
      { emoji: '🤓', name: 'nerd', keywords: ['nerd'] },
      { emoji: '🧐', name: 'monocle', keywords: ['slim'] },
      { emoji: '🤔', name: 'thinking', keywords: ['think', 'nadenken'] },
      { emoji: '🤨', name: 'raised_eyebrow', keywords: ['sus', 'hmmm'] },
      { emoji: '😐', name: 'neutral_face', keywords: ['meh', 'neutraal', ':|', ':-|'] },
      { emoji: '😑', name: 'expressionless', keywords: ['meh'] },
      { emoji: '😶', name: 'no_mouth', keywords: ['stil'] },
      { emoji: '🙄', name: 'roll_eyes', keywords: ['roll', 'zucht'] },
      { emoji: '😏', name: 'smirk', keywords: ['smirk', 'grijns'] },
      { emoji: '😣', name: 'persevere', keywords: ['pijn'] },
      { emoji: '😥', name: 'sad_but_relieved', keywords: ['sad', 'opgelucht'] },
      { emoji: '😮', name: 'open_mouth', keywords: ['wow', 'verbaasd', ':O', ':o', ':-O', ':-o'] },
      { emoji: '🤐', name: 'zipper_mouth', keywords: ['stil', 'geheim'] },
      { emoji: '😯', name: 'hushed', keywords: ['wow'] },
      { emoji: '😪', name: 'sleepy', keywords: ['slaap'] },
      { emoji: '😫', name: 'tired_face', keywords: ['moe'] },
      { emoji: '🤤', name: 'drooling', keywords: ['lekker'] },
      { emoji: '😒', name: 'unamused', keywords: ['meh'] },
      { emoji: '😓', name: 'sweat', keywords: ['stress'] },
      { emoji: '😔', name: 'pensive', keywords: ['sad'] },
      { emoji: '😕', name: 'confused', keywords: ['verward', ':/', ':-/'] },
      { emoji: '😲', name: 'astonished', keywords: ['wow'] },
      { emoji: '☹️', name: 'frowning', keywords: ['sad'] },
      { emoji: '🙁', name: 'slight_frown', keywords: ['sad'] },
      { emoji: '😖', name: 'confounded', keywords: ['pijn'] },
      { emoji: '😞', name: 'disappointed', keywords: ['sad'] },
      { emoji: '😟', name: 'worried', keywords: ['bang'] },
      { emoji: '😤', name: 'triumph', keywords: ['boos'] },
      { emoji: '😢', name: 'cry', keywords: ['huilen'] },
      { emoji: '😭', name: 'sob', keywords: ['huilen'] },
      { emoji: '😦', name: 'frowning_with_open_mouth', keywords: ['wow'] },
      { emoji: '😧', name: 'anguished', keywords: ['wow'] },
      { emoji: '😨', name: 'fearful', keywords: ['bang'] },
      { emoji: '😩', name: 'weary', keywords: ['moe'] },
      { emoji: '🤯', name: 'exploding_head', keywords: ['mindblown'] },
      { emoji: '😬', name: 'grimacing', keywords: ['oeps'] },
      { emoji: '😰', name: 'cold_sweat', keywords: ['bang'] },
      { emoji: '😱', name: 'scream', keywords: ['bang'] },
      { emoji: '🥵', name: 'hot_face', keywords: ['heet'] },
      { emoji: '🥶', name: 'cold_face', keywords: ['koud'] },
      { emoji: '😳', name: 'flushed', keywords: ['bloos', ':$', ':-$'] },
      { emoji: '🤪', name: 'zany_face', keywords: ['gek'] },
      { emoji: '😵', name: 'dizzy_face', keywords: ['duizelig'] },
      { emoji: '😡', name: 'rage', keywords: ['boos'] },
      { emoji: '😠', name: 'angry', keywords: ['boos'] },
      { emoji: '🤬', name: 'cursing', keywords: ['boos'] },
      { emoji: '😷', name: 'mask', keywords: ['ziek'] },
      { emoji: '🤒', name: 'thermometer', keywords: ['ziek'] },
      { emoji: '🤕', name: 'bandage', keywords: ['ziek'] },
      { emoji: '🤢', name: 'nauseated', keywords: ['vies'] },
      { emoji: '🤮', name: 'vomiting', keywords: ['vies'] },
      { emoji: '🤧', name: 'sneezing', keywords: ['ziek'] },
      { emoji: '🤠', name: 'cowboy', keywords: ['cowboy'] },
      { emoji: '🤡', name: 'clown', keywords: ['clown'] },
      { emoji: '🥳', name: 'party', keywords: ['feest'] },
      { emoji: '🥴', name: 'woozy', keywords: ['dronken'] },
      { emoji: '🥺', name: 'pleading', keywords: ['lief'] },
      { emoji: '🤥', name: 'lying', keywords: ['leugen'] },
      { emoji: '🤫', name: 'shushing', keywords: ['stil'] },
      { emoji: '🤭', name: 'hand_over_mouth', keywords: ['oeps'] },
      { emoji: '😈', name: 'smiling_imp', keywords: ['duivel'] },
      { emoji: '👿', name: 'imp', keywords: ['duivel'] },
      { emoji: '👹', name: 'ogre', keywords: ['monster'] },
      { emoji: '👺', name: 'goblin', keywords: ['monster'] },
      { emoji: '💀', name: 'skull', keywords: ['dood'] },
      { emoji: '☠️', name: 'skull_crossbones', keywords: ['dead', 'toxic'] },
      { emoji: '👻', name: 'ghost', keywords: ['geest'] },
      { emoji: '👽', name: 'alien', keywords: ['alien'] },
      { emoji: '👾', name: 'alien_monster', keywords: ['game'] },
      { emoji: '🤖', name: 'robot', keywords: ['robot'] },
      { emoji: '💩', name: 'poop', keywords: ['poep'] },
      { emoji: '👋', name: 'wave', keywords: ['zwaaien'] },
      { emoji: '🤚', name: 'raised_back_of_hand', keywords: ['stop'] },
      { emoji: '🖐️', name: 'hand_splayed', keywords: ['stop'] },
      { emoji: '✋', name: 'hand', keywords: ['stop'] },
      { emoji: '🖖', name: 'vulcan', keywords: ['spock'] },
      { emoji: '👌', name: 'ok_hand', keywords: ['ok'] },
      { emoji: '🤌', name: 'pinched_fingers', keywords: ['italian'] },
      { emoji: '🤏', name: 'pinching_hand', keywords: ['beetje'] },
      { emoji: '✌️', name: 'v', keywords: ['peace'] },
      { emoji: '🤞', name: 'fingers_crossed', keywords: ['hoop'] },
      { emoji: '🤟', name: 'love_you', keywords: ['love'] },
      { emoji: '🤘', name: 'metal', keywords: ['rock'] },
      { emoji: '🤙', name: 'call_me', keywords: ['bellen'] },
      { emoji: '👈', name: 'point_left', keywords: ['links'] },
      { emoji: '👉', name: 'point_right', keywords: ['rechts'] },
      { emoji: '👆', name: 'point_up', keywords: ['boven'] },
      { emoji: '🖕', name: 'middle_finger', keywords: ['middelvinger'] },
      { emoji: '👇', name: 'point_down', keywords: ['onder'] },
      { emoji: '☝️', name: 'point_up_2', keywords: ['boven'] },
      { emoji: '👍', name: '+1', keywords: ['goed'] },
      { emoji: '👎', name: '-1', keywords: ['slecht'] },
      { emoji: '✊', name: 'fist_raised', keywords: ['power'] },
      { emoji: '👊', name: 'fist', keywords: ['boks'] },
      { emoji: '🤛', name: 'fist_left', keywords: ['boks'] },
      { emoji: '🤜', name: 'fist_right', keywords: ['boks'] },
      { emoji: '👏', name: 'clapping', keywords: ['klappen'] },
      { emoji: '🙌', name: 'raised_hands', keywords: ['feest'] },
      { emoji: '👐', name: 'open_hands', keywords: ['open'] },
      { emoji: '🤲', name: 'palms_up', keywords: ['gebed'] },
      { emoji: '🤝', name: 'handshake', keywords: ['deal'] },
      { emoji: '🙏', name: 'pray', keywords: ['bidden'] },
      { emoji: '💅', name: 'nail_polish', keywords: ['nagels'] },
      { emoji: '🤳', name: 'selfie', keywords: ['selfie'] },
      { emoji: '💪', name: 'muscle', keywords: ['sterk'] },
      { emoji: '🦾', name: 'mechanical_arm', keywords: ['robot'] },
      { emoji: '🦿', name: 'mechanical_leg', keywords: ['robot'] },
      { emoji: '🦵', name: 'leg', keywords: ['been'] },
      { emoji: '🦶', name: 'foot', keywords: ['voet'] },
      { emoji: '👂', name: 'ear', keywords: ['oor'] },
      { emoji: '🦻', name: 'hearing_aid', keywords: ['oor'] },
      { emoji: '👃', name: 'nose', keywords: ['neus'] },
      { emoji: '🧠', name: 'brain', keywords: ['hersenen'] },
      { emoji: '🫀', name: 'anatomical_heart', keywords: ['hart'] },
      { emoji: '🫁', name: 'lungs', keywords: ['longen'] },
      { emoji: '🦷', name: 'tooth', keywords: ['tand'] },
      { emoji: '🦴', name: 'bone', keywords: ['bot'] },
      { emoji: '👀', name: 'eyes', keywords: ['ogen'] },
      { emoji: '👁️', name: 'eye', keywords: ['oog'] },
      { emoji: '👅', name: 'tongue', keywords: ['tong'] },
      { emoji: '👄', name: 'lips', keywords: ['mond'] },
    ]
  },
  {
    id: 'nature',
    name: 'Dieren & Natuur',
    icon: '🐶',
    emojis: [
      { emoji: '🐶', name: 'dog', keywords: ['hond', 'woef'] },
      { emoji: '🐱', name: 'cat', keywords: ['kat', 'miauw'] },
      { emoji: '🐭', name: 'mouse', keywords: ['muis'] },
      { emoji: '🐹', name: 'hamster', keywords: ['hamster'] },
      { emoji: '🐰', name: 'rabbit', keywords: ['konijn'] },
      { emoji: '🦊', name: 'fox', keywords: ['vos'] },
      { emoji: '🐻', name: 'bear', keywords: ['beer'] },
      { emoji: '🐼', name: 'panda', keywords: ['panda'] },
      { emoji: '🐨', name: 'koala', keywords: ['koala'] },
      { emoji: '🐯', name: 'tiger', keywords: ['tijger'] },
      { emoji: '🦁', name: 'lion', keywords: ['leeuw'] },
      { emoji: '🐮', name: 'cow', keywords: ['koe'] },
      { emoji: '🐷', name: 'pig', keywords: ['varken'] },
      { emoji: '🐸', name: 'frog', keywords: ['kikker'] },
      { emoji: '🐵', name: 'monkey', keywords: ['aap'] },
      { emoji: '🙊', name: 'speak_no_evil', keywords: ['aap', 'stil'] },
      { emoji: '🙉', name: 'hear_no_evil', keywords: ['aap', 'stil'] },
      { emoji: '🙈', name: 'see_no_evil', keywords: ['aap', 'oeps'] },
      { emoji: '🐔', name: 'chicken', keywords: ['kip'] },
      { emoji: '🐧', name: 'penguin', keywords: ['pinguin'] },
      { emoji: '🐦', name: 'bird', keywords: ['vogel'] },
      { emoji: '🐤', name: 'baby_chick', keywords: ['kip'] },
      { emoji: '🦆', name: 'duck', keywords: ['eend'] },
      { emoji: '🦅', name: 'eagle', keywords: ['arend'] },
      { emoji: '🦉', name: 'owl', keywords: ['uil'] },
      { emoji: '🦇', name: 'bat', keywords: ['vleermuis'] },
      { emoji: '🐺', name: 'wolf', keywords: ['wolf'] },
      { emoji: '🐗', name: 'boar', keywords: ['zwijn'] },
      { emoji: '🐴', name: 'horse', keywords: ['paard'] },
      { emoji: '🦄', name: 'unicorn', keywords: ['unicorn'] },
      { emoji: '🐝', name: 'bee', keywords: ['bij'] },
      { emoji: '🐛', name: 'bug', keywords: ['rups'] },
      { emoji: '🦋', name: 'butterfly', keywords: ['vlinder'] },
      { emoji: '🐌', name: 'snail', keywords: ['slak'] },
      { emoji: '🐞', name: 'lady_beetle', keywords: ['lieveheersbeestje'] },
      { emoji: '🐜', name: 'ant', keywords: ['mier'] },
      { emoji: '🦗', name: 'cricket', keywords: ['krekel'] },
      { emoji: '🕷️', name: 'spider', keywords: ['spin'] },
      { emoji: '🕸️', name: 'spider_web', keywords: ['web'] },
      { emoji: '🦂', name: 'scorpion', keywords: ['schorpioen'] },
      { emoji: '🐢', name: 'turtle', keywords: ['schildpad'] },
      { emoji: '🐍', name: 'snake', keywords: ['slang'] },
      { emoji: '🦎', name: 'lizard', keywords: ['hagedis'] },
      { emoji: '🦖', name: 't-rex', keywords: ['dino'] },
      { emoji: '🦕', name: 'brachiosaurus', keywords: ['dino'] },
      { emoji: '🐙', name: 'octopus', keywords: ['octopus'] },
      { emoji: '🦑', name: 'squid', keywords: ['inktvis'] },
      { emoji: '🦐', name: 'shrimp', keywords: ['garnaal'] },
      { emoji: '🦞', name: 'lobster', keywords: ['kreeft'] },
      { emoji: '🦀', name: 'crab', keywords: ['krab'] },
      { emoji: '🐡', name: 'blowfish', keywords: ['vis'] },
      { emoji: '🐠', name: 'tropical_fish', keywords: ['vis'] },
      { emoji: '🐟', name: 'fish', keywords: ['vis'] },
      { emoji: '🐬', name: 'dolphin', keywords: ['dolfijn'] },
      { emoji: '🐳', name: 'whale', keywords: ['walvis'] },
      { emoji: '🦈', name: 'shark', keywords: ['haai'] },
      { emoji: '🐊', name: 'crocodile', keywords: ['krokodil'] },
      { emoji: '🐅', name: 'tiger2', keywords: ['tijger'] },
      { emoji: '🐆', name: 'leopard', keywords: ['panter'] },
      { emoji: '🦓', name: 'zebra', keywords: ['zebra'] },
      { emoji: '🦍', name: 'gorilla', keywords: ['gorilla'] },
      { emoji: '🐘', name: 'elephant', keywords: ['olifant'] },
      { emoji: '🦏', name: 'rhinoceros', keywords: ['neushoorn'] },
      { emoji: '🐪', name: 'camel', keywords: ['kameel'] },
      { emoji: '🦒', name: 'giraffe', keywords: ['giraffe'] },
      { emoji: '🦘', name: 'kangaroo', keywords: ['kangoeroe'] },
      { emoji: '🐃', name: 'water_buffalo', keywords: ['buffel'] },
      { emoji: '🐄', name: 'cow2', keywords: ['koe'] },
      { emoji: '🐎', name: 'horse2', keywords: ['paard'] },
      { emoji: '🐖', name: 'pig2', keywords: ['varken'] },
      { emoji: '🐏', name: 'ram', keywords: ['schaap'] },
      { emoji: '🐑', name: 'sheep', keywords: ['schaap'] },
      { emoji: '🐐', name: 'goat', keywords: ['geit'] },
      { emoji: '🦌', name: 'deer', keywords: ['hert'] },
      { emoji: '🐕', name: 'dog2', keywords: ['hond'] },
      { emoji: '🐩', name: 'poodle', keywords: ['hond'] },
      { emoji: '🐈', name: 'cat2', keywords: ['kat'] },
      { emoji: '🐓', name: 'rooster', keywords: ['haan'] },
      { emoji: '🦃', name: 'turkey', keywords: ['kalkoen'] },
      { emoji: '🕊️', name: 'dove', keywords: ['duif'] },
      { emoji: '🐇', name: 'rabbit2', keywords: ['konijn'] },
      { emoji: '🐁', name: 'mouse2', keywords: ['muis'] },
      { emoji: '🐀', name: 'rat', keywords: ['rat'] },
      { emoji: '🐿️', name: 'chipmunk', keywords: ['eekhoorn'] },
      { emoji: '🦥', name: 'sloth', keywords: ['luiaard'] },
      { emoji: '🦔', name: 'hedgehog', keywords: ['egel'] },
      { emoji: '🐾', name: 'paw_prints', keywords: ['poot'] },
      { emoji: '🐉', name: 'dragon', keywords: ['draak'] },
      { emoji: '🌵', name: 'cactus', keywords: ['cactus'] },
      { emoji: '🎄', name: 'christmas_tree', keywords: ['boom', 'kerst'] },
      { emoji: '🌲', name: 'evergreen_tree', keywords: ['boom'] },
      { emoji: '🌳', name: 'deciduous_tree', keywords: ['boom'] },
      { emoji: '🌴', name: 'palm_tree', keywords: ['palm'] },
      { emoji: '🌱', name: 'seedling', keywords: ['plant'] },
      { emoji: '🌿', name: 'herb', keywords: ['plant'] },
      { emoji: '☘️', name: 'shamrock', keywords: ['klaver'] },
      { emoji: '🍀', name: 'four_leaf_clover', keywords: ['geluk'] },
      { emoji: '🍁', name: 'maple_leaf', keywords: ['blad'] },
      { emoji: '🍂', name: 'fallen_leaf', keywords: ['blad'] },
      { emoji: '🍃', name: 'leaves', keywords: ['blaadjes'] },
      { emoji: '🍄', name: 'mushroom', keywords: ['paddenstoel'] },
      { emoji: '🌹', name: 'rose', keywords: ['roos'] },
      { emoji: '🌷', name: 'tulip', keywords: ['tulp'] },
      { emoji: '🌼', name: 'blossom', keywords: ['bloem'] },
      { emoji: '🌻', name: 'sunflower', keywords: ['zonnebloem'] },
      { emoji: '🌞', name: 'sun_with_face', keywords: ['zon'] },
      { emoji: '🌝', name: 'full_moon_with_face', keywords: ['maan'] },
      { emoji: '🌛', name: 'first_quarter_moon_with_face', keywords: ['maan'] },
      { emoji: '🌙', name: 'moon', keywords: ['maan'] },
      { emoji: '⭐', name: 'star', keywords: ['ster'] },
      { emoji: '🌟', name: 'star2', keywords: ['ster'] },
      { emoji: '💫', name: 'dizzy', keywords: ['sterren'] },
      { emoji: '✨', name: 'sparkles', keywords: ['mooi'] },
      { emoji: '☄️', name: 'comet', keywords: ['komeet'] },
      { emoji: '☀️', name: 'sun', keywords: ['zon'] },
      { emoji: '🌤️', name: 'sun_behind_small_cloud', keywords: ['weer'] },
      { emoji: '⛅', name: 'partly_sunny', keywords: ['weer'] },
      { emoji: '☁️', name: 'cloud', keywords: ['wolk'] },
      { emoji: '🌧️', name: 'cloud_with_rain', keywords: ['regen'] },
      { emoji: '⛈️', name: 'cloud_with_lightning_and_rain', keywords: ['onweer'] },
      { emoji: '🌩️', name: 'cloud_with_lightning', keywords: ['bliksem'] },
      { emoji: '❄️', name: 'snowflake', keywords: ['sneeuw'] },
      { emoji: '💨', name: 'dash', keywords: ['wind'] },
      { emoji: '🌈', name: 'rainbow', keywords: ['regenboog'] },
      { emoji: '🌊', name: 'ocean', keywords: ['zee'] },
      { emoji: '💧', name: 'droplet', keywords: ['water'] },
      { emoji: '🔥', name: 'fire', keywords: ['vuur', 'heet'] },
    ]
  },
  {
    id: 'food',
    name: 'Eten & Drinken',
    icon: '🍎',
    emojis: [
      { emoji: '🍏', name: 'green_apple', keywords: ['appel'] },
      { emoji: '🍎', name: 'apple', keywords: ['appel'] },
      { emoji: '🍐', name: 'pear', keywords: ['peer'] },
      { emoji: '🍊', name: 'tangerine', keywords: ['sinaasappel'] },
      { emoji: '🍋', name: 'lemon', keywords: ['citroen'] },
      { emoji: '🍌', name: 'banana', keywords: ['banaan'] },
      { emoji: '🍉', name: 'watermelon', keywords: ['meloen'] },
      { emoji: '🍇', name: 'grapes', keywords: ['druiven'] },
      { emoji: '🍓', name: 'strawberry', keywords: ['aardbei'] },
      { emoji: '🫐', name: 'blueberries', keywords: ['bessen'] },
      { emoji: '🍈', name: 'melon', keywords: ['meloen'] },
      { emoji: '🍒', name: 'cherries', keywords: ['kersen'] },
      { emoji: '🍑', name: 'peach', keywords: ['perzik'] },
      { emoji: '🥭', name: 'mango', keywords: ['mango'] },
      { emoji: '🍍', name: 'pineapple', keywords: ['ananas'] },
      { emoji: '🥥', name: 'coconut', keywords: ['kokosnoot'] },
      { emoji: '🥝', name: 'kiwi', keywords: ['kiwi'] },
      { emoji: '🍅', name: 'tomato', keywords: ['tomaat'] },
      { emoji: '🍆', name: 'eggplant', keywords: ['aubergine'] },
      { emoji: '🥑', name: 'avocado', keywords: ['avocado'] },
      { emoji: '🥦', name: 'broccoli', keywords: ['broccoli'] },
      { emoji: '🥬', name: 'leafy_green', keywords: ['sla'] },
      { emoji: '🥒', name: 'cucumber', keywords: ['komkommer'] },
      { emoji: '🌶️', name: 'hot_pepper', keywords: ['peper'] },
      { emoji: '🌽', name: 'corn', keywords: ['mais'] },
      { emoji: '🥕', name: 'carrot', keywords: ['wortel'] },
      { emoji: '🫑', name: 'bell_pepper', keywords: ['paprika'] },
      { emoji: '🥔', name: 'potato', keywords: ['aardappel'] },
      { emoji: '🍠', name: 'sweet_potato', keywords: ['aardappel'] },
      { emoji: '🥐', name: 'croissant', keywords: ['brood'] },
      { emoji: '🥖', name: 'baguette_bread', keywords: ['stokbrood'] },
      { emoji: '🥨', name: 'pretzel', keywords: ['krakeling'] },
      { emoji: '🥯', name: 'bagel', keywords: ['brood'] },
      { emoji: '🥞', name: 'pancakes', keywords: ['pannenkoek'] },
      { emoji: '🧇', name: 'waffle', keywords: ['wafel'] },
      { emoji: '🧀', name: 'cheese', keywords: ['kaas'] },
      { emoji: '🍖', name: 'meat_on_bone', keywords: ['vlees'] },
      { emoji: '🍗', name: 'poultry_leg', keywords: ['kip'] },
      { emoji: '🥩', name: 'steak', keywords: ['vlees'] },
      { emoji: '🥓', name: 'bacon', keywords: ['spek'] },
      { emoji: '🍔', name: 'hamburger', keywords: ['burger'] },
      { emoji: '🍟', name: 'french_fries', keywords: ['patat'] },
      { emoji: '🍕', name: 'pizza', keywords: ['pizza'] },
      { emoji: '🌭', name: 'hotdog', keywords: ['hotdog'] },
      { emoji: '🥪', name: 'sandwich', keywords: ['broodje'] },
      { emoji: '🌮', name: 'taco', keywords: ['taco'] },
      { emoji: '🌯', name: 'burrito', keywords: ['burrito'] },
      { emoji: '🍳', name: 'egg', keywords: ['ei'] },
      { emoji: '🥘', name: 'shallow_pan_of_food', keywords: ['eten'] },
      { emoji: '🍲', name: 'stew', keywords: ['soep'] },
      { emoji: '🥣', name: 'bowl_with_spoon', keywords: ['eten'] },
      { emoji: '🥗', name: 'salad', keywords: ['salade'] },
      { emoji: '🍿', name: 'popcorn', keywords: ['popcorn'] },
      { emoji: '🧈', name: 'butter', keywords: ['boter'] },
      { emoji: '🧂', name: 'salt', keywords: ['zout'] },
      { emoji: '🥫', name: 'canned_food', keywords: ['blik'] },
      { emoji: '🍱', name: 'bento', keywords: ['eten'] },
      { emoji: '🍘', name: 'rice_cracker', keywords: ['eten'] },
      { emoji: '🍙', name: 'rice_ball', keywords: ['eten'] },
      { emoji: '🍚', name: 'rice', keywords: ['rijst'] },
      { emoji: '🍛', name: 'curry', keywords: ['kerrie'] },
      { emoji: '🍜', name: 'ramen', keywords: ['noedels'] },
      { emoji: '🍝', name: 'spaghetti', keywords: ['pasta'] },
      { emoji: '🍠', name: 'sweet_potato', keywords: ['aardappel'] },
      { emoji: '🍢', name: 'oden', keywords: ['eten'] },
      { emoji: '🍣', name: 'sushi', keywords: ['sushi'] },
      { emoji: '🍤', name: 'fried_shrimp', keywords: ['garnaal'] },
      { emoji: '🍥', name: 'fish_cake', keywords: ['eten'] },
      { emoji: '🥠', name: 'fortune_cookie', keywords: ['koekje'] },
      { emoji: '🥮', name: 'moon_cake', keywords: ['eten'] },
      { emoji: '🍡', name: 'dango', keywords: ['eten'] },
      { emoji: '🥟', name: 'dumpling', keywords: ['eten'] },
      { emoji: '🥠', name: 'fortune_cookie', keywords: ['koekje'] },
      { emoji: '🍦', name: 'ice_cream', keywords: ['ijs'] },
      { emoji: '🍧', name: 'shaved_ice', keywords: ['ijs'] },
      { emoji: '🍨', name: 'icecream', keywords: ['ijs'] },
      { emoji: '🍩', name: 'donut', keywords: ['donut'] },
      { emoji: '🍪', name: 'cookie', keywords: ['koekje'] },
      { emoji: '🎂', name: 'birthday', keywords: ['taart'] },
      { emoji: '🍰', name: 'cake', keywords: ['taart'] },
      { emoji: '🧁', name: 'cupcake', keywords: ['cupcake'] },
      { emoji: '🥧', name: 'pie', keywords: ['taart'] },
      { emoji: '🍫', name: 'chocolate_bar', keywords: ['chocolade'] },
      { emoji: '🍬', name: 'candy', keywords: ['snoep'] },
      { emoji: '🍭', name: 'lollipop', keywords: ['snoep'] },
      { emoji: '🍮', name: 'custard', keywords: ['pudding'] },
      { emoji: '🍯', name: 'honey_pot', keywords: ['honing'] },
      { emoji: '🍼', name: 'baby_bottle', keywords: ['melk'] },
      { emoji: '🥛', name: 'milk_glass', keywords: ['melk'] },
      { emoji: '☕', name: 'coffee', keywords: ['koffie'] },
      { emoji: '🫖', name: 'teapot', keywords: ['thee'] },
      { emoji: '🍵', name: 'tea', keywords: ['thee'] },
      { emoji: '🍶', name: 'sake', keywords: ['drinken'] },
      { emoji: '🍾', name: 'champagne', keywords: ['feest'] },
      { emoji: '🍷', name: 'wine_glass', keywords: ['wijn'] },
      { emoji: '🍸', name: 'cocktail', keywords: ['cocktail'] },
      { emoji: '🍹', name: 'tropical_drink', keywords: ['cocktail'] },
      { emoji: '🍺', name: 'beer', keywords: ['bier'] },
      { emoji: '🍻', name: 'beers', keywords: ['bier'] },
      { emoji: '🥂', name: 'clinking_glasses', keywords: ['proost'] },
      { emoji: '🥃', name: 'tumbler_glass', keywords: ['whisky'] },
      { emoji: '🥤', name: 'cup_with_straw', keywords: ['frisdrank'] },
      { emoji: '🧋', name: 'bubble_tea', keywords: ['thee'] },
      { emoji: '🧃', name: 'juice_box', keywords: ['sap'] },
      { emoji: '🧉', name: 'mate', keywords: ['drinken'] },
      { emoji: '🧊', name: 'ice_cube', keywords: ['ijs'] },
    ]
  },
  {
    id: 'activity',
    name: 'Activiteiten',
    icon: '⚽',
    emojis: [
      { emoji: '⚽', name: 'soccer', keywords: ['voetbal'] },
      { emoji: '🏀', name: 'basketball', keywords: ['basketbal'] },
      { emoji: '🏈', name: 'football', keywords: ['rugby'] },
      { emoji: '⚾', name: 'baseball', keywords: ['honkbal'] },
      { emoji: '🥎', name: 'softball', keywords: ['softbal'] },
      { emoji: '🎾', name: 'tennis', keywords: ['tennis'] },
      { emoji: '🏐', name: 'volleyball', keywords: ['volleybal'] },
      { emoji: '🏉', name: 'rugby_football', keywords: ['rugby'] },
      { emoji: '🎱', name: '8ball', keywords: ['biljart'] },
      { emoji: '🏓', name: 'ping_pong', keywords: ['tafeltennis'] },
      { emoji: '🏸', name: 'badminton', keywords: ['badminton'] },
      { emoji: '🏒', name: 'ice_hockey', keywords: ['ijshockey'] },
      { emoji: '🏑', name: 'field_hockey', keywords: ['hockey'] },
      { emoji: '🏏', name: 'cricket_game', keywords: ['cricket'] },
      { emoji: '🥅', name: 'goal_net', keywords: ['doel'] },
      { emoji: '⛳', name: 'golf', keywords: ['golf'] },
      { emoji: '🏹', name: 'bow_and_arrow', keywords: ['boogschieten'] },
      { emoji: '🎣', name: 'fishing_pole', keywords: ['vissen'] },
      { emoji: '🤿', name: 'diving_mask', keywords: ['duiken'] },
      { emoji: '🥊', name: 'boxing_glove', keywords: ['boksen'] },
      { emoji: '🥋', name: 'martial_arts_uniform', keywords: ['karate'] },
      { emoji: '⛸️', name: 'ice_skate', keywords: ['schaatsen'] },
      { emoji: '🎿', name: 'ski', keywords: ['ski'] },
      { emoji: '🛷', name: 'sled', keywords: ['slee'] },
      { emoji: '🥌', name: 'curling_stone', keywords: ['curling'] },
      { emoji: '🎯', name: 'darts', keywords: ['darten'] },
      { emoji: '🪀', name: 'yo-yo', keywords: ['jojo'] },
      { emoji: '🪁', name: 'kite', keywords: ['vlieger'] },
      { emoji: '🔫', name: 'gun', keywords: ['pistool'] },
      { emoji: '🎮', name: 'video_game', keywords: ['games'] },
      { emoji: '🕹️', name: 'joystick', keywords: ['games'] },
      { emoji: '🎰', name: 'slot_machine', keywords: ['casino'] },
      { emoji: '🎲', name: 'game_die', keywords: ['dobbelsteen'] },
      { emoji: '🧩', name: 'puzzle', keywords: ['puzzel'] },
      { emoji: '🧸', name: 'teddy_bear', keywords: ['beer'] },
      { emoji: '♠️', name: 'spades', keywords: ['kaarten'] },
      { emoji: '♥️', name: 'hearts', keywords: ['kaarten'] },
      { emoji: '♦️', name: 'diamonds', keywords: ['kaarten'] },
      { emoji: '♣️', name: 'clubs', keywords: ['kaarten'] },
      { emoji: '♟️', name: 'chess_pawn', keywords: ['schaken'] },
      { emoji: '🎭', name: 'theater', keywords: ['drama'] },
      { emoji: '🎨', name: 'art', keywords: ['schilderen'] },
      { emoji: '🧵', name: 'thread', keywords: ['naaien'] },
      { emoji: '🧶', name: 'yarn', keywords: ['breien'] },
      { emoji: '🎸', name: 'guitar', keywords: ['gitaar'] },
      { emoji: '🎹', name: 'keyboard', keywords: ['piano'] },
      { emoji: '🎺', name: 'trumpet', keywords: ['trompet'] },
      { emoji: '🎻', name: 'violin', keywords: ['viool'] },
      { emoji: '🥁', name: 'drum', keywords: ['drums'] },
      { emoji: '🎬', name: 'clapper', keywords: ['film'] },
      { emoji: '🎤', name: 'microphone', keywords: ['zingen'] },
      { emoji: '🎧', name: 'headphones', keywords: ['muziek'] },
      { emoji: '🎷', name: 'saxophone', keywords: ['saxofoon'] },
    ]
  },
  {
    id: 'travel',
    name: 'Reizen & Plaatsen',
    icon: '✈️',
    emojis: [
      { emoji: '🌍', name: 'earth_africa', keywords: ['wereld'] },
      { emoji: '🌎', name: 'earth_americas', keywords: ['wereld'] },
      { emoji: '🌏', name: 'earth_asia', keywords: ['wereld'] },
      { emoji: '🌐', name: 'globe_with_meridians', keywords: ['web'] },
      { emoji: '🗺️', name: 'world_map', keywords: ['kaart'] },
      { emoji: '🗾', name: 'japan', keywords: ['japan'] },
      { emoji: '🧭', name: 'compass', keywords: ['kompas'] },
      { emoji: '🏔️', name: 'mountain_snow', keywords: ['bergen'] },
      { emoji: '⛰️', name: 'mountain', keywords: ['bergen'] },
      { emoji: '🌋', name: 'volcano', keywords: ['vulkaan'] },
      { emoji: '🗻', name: 'mount_fuji', keywords: ['berg'] },
      { emoji: '🏕️', name: 'camping', keywords: ['kamperen'] },
      { emoji: '🏖️', name: 'beach_umbrella', keywords: ['strand'] },
      { emoji: '🏜️', name: 'desert', keywords: ['woestijn'] },
      { emoji: '🏝️', name: 'island', keywords: ['eiland'] },
      { emoji: '🏞️', name: 'national_park', keywords: ['natuur'] },
      { emoji: '🏟️', name: 'stadium', keywords: ['stadion'] },
      { emoji: '🏛️', name: 'classical_building', keywords: ['gebouw'] },
      { emoji: '🏗️', name: 'building_construction', keywords: ['bouw'] },
      { emoji: '🧱', name: 'brick', keywords: ['steen'] },
      { emoji: '🏠', name: 'house', keywords: ['huis'] },
      { emoji: '🏡', name: 'house_with_garden', keywords: ['huis'] },
      { emoji: '🏢', name: 'office', keywords: ['kantoor'] },
      { emoji: '🏣', name: 'japanese_post_office', keywords: ['post'] },
      { emoji: '🏤', name: 'post_office', keywords: ['post'] },
      { emoji: '🏥', name: 'hospital', keywords: ['ziekenhuis'] },
      { emoji: '🏦', name: 'bank', keywords: ['bank'] },
      { emoji: '🏨', name: 'hotel', keywords: ['hotel'] },
      { emoji: '🏩', name: 'love_hotel', keywords: ['hotel'] },
      { emoji: '🏪', name: 'convenience_store', keywords: ['winkel'] },
      { emoji: '🏫', name: 'school', keywords: ['school'] },
      { emoji: '🏬', name: 'department_store', keywords: ['winkel'] },
      { emoji: '🏭', name: 'factory', keywords: ['fabriek'] },
      { emoji: '🏯', name: 'japanese_castle', keywords: ['kasteel'] },
      { emoji: '🏰', name: 'castle', keywords: ['kasteel'] },
      { emoji: '💒', name: 'wedding', keywords: ['bruiloft'] },
      { emoji: '🗼', name: 'tokyo_tower', keywords: ['toren'] },
      { emoji: '🗽', name: 'statue_of_liberty', keywords: ['vrijheid'] },
      { emoji: '⛪', name: 'church', keywords: ['kerk'] },
      { emoji: '🕌', name: 'mosque', keywords: ['moskee'] },
      { emoji: '🛕', name: 'hindu_temple', keywords: ['tempel'] },
      { emoji: '🕍', name: 'synagogue', keywords: ['synagoge'] },
      { emoji: '⛩️', name: 'shinto_shrine', keywords: ['tempel'] },
      { emoji: '🕋', name: 'kaaba', keywords: ['mekka'] },
      { emoji: '⛲', name: 'fountain', keywords: ['fontein'] },
      { emoji: '⛺', name: 'tent', keywords: ['tent'] },
      { emoji: '🌁', name: 'foggy', keywords: ['mist'] },
      { emoji: '🌃', name: 'night_with_stars', keywords: ['nacht'] },
      { emoji: '🏙️', name: 'cityscape', keywords: ['stad'] },
      { emoji: '🌄', name: 'sunrise_over_mountains', keywords: ['zonsopkomst'] },
      { emoji: '🌅', name: 'sunrise', keywords: ['zonsopkomst'] },
      { emoji: '🌆', name: 'city_sunset', keywords: ['stad'] },
      { emoji: '🌇', name: 'sunset', keywords: ['zonsondergang'] },
      { emoji: '🌉', name: 'bridge_at_night', keywords: ['brug'] },
      { emoji: '♨️', name: 'hotsprings', keywords: ['sauna'] },
      { emoji: '🎠', name: 'carousel_horse', keywords: ['kermis'] },
      { emoji: '🎡', name: 'ferris_wheel', keywords: ['kermis'] },
      { emoji: '🎢', name: 'roller_coaster', keywords: ['achtbaan'] },
      { emoji: '💈', name: 'barber', keywords: ['kapper'] },
      { emoji: '🎪', name: 'circus_tent', keywords: ['circus'] },
      { emoji: '🚂', name: 'steam_locomotive', keywords: ['trein'] },
      { emoji: '🚃', name: 'railway_car', keywords: ['trein'] },
      { emoji: '🚄', name: 'bullettrain_side', keywords: ['trein'] },
      { emoji: '🚅', name: 'bullettrain_front', keywords: ['trein'] },
      { emoji: '🚆', name: 'train2', keywords: ['trein'] },
      { emoji: '🚇', name: 'metro', keywords: ['metro'] },
      { emoji: '🚈', name: 'light_rail', keywords: ['trein'] },
      { emoji: '🚉', name: 'station', keywords: ['trein'] },
      { emoji: '🚊', name: 'tram', keywords: ['tram'] },
      { emoji: '🚝', name: 'monorail', keywords: ['monorail'] },
      { emoji: '🚞', name: 'mountain_railway', keywords: ['trein'] },
      { emoji: '🚋', name: 'tram_car', keywords: ['tram'] },
      { emoji: '🚌', name: 'bus', keywords: ['bus'] },
      { emoji: '🚍', name: 'oncoming_bus', keywords: ['bus'] },
      { emoji: '🚎', name: 'trolleybus', keywords: ['bus'] },
      { emoji: '🚐', name: 'minibus', keywords: ['busje'] },
      { emoji: '🚑', name: 'ambulance', keywords: ['ziekenauto'] },
      { emoji: '🚒', name: 'fire_engine', keywords: ['brandweer'] },
      { emoji: '🚓', name: 'police_car', keywords: ['politie'] },
      { emoji: '🚔', name: 'oncoming_police_car', keywords: ['politie'] },
      { emoji: '🚕', name: 'taxi', keywords: ['taxi'] },
      { emoji: '🚖', name: 'oncoming_taxi', keywords: ['taxi'] },
      { emoji: '🚗', name: 'red_car', keywords: ['auto'] },
      { emoji: '🚘', name: 'oncoming_automobile', keywords: ['auto'] },
      { emoji: '🚙', name: 'blue_car', keywords: ['auto'] },
      { emoji: '🚚', name: 'delivery_truck', keywords: ['vrachtwagen'] },
      { emoji: '🚛', name: 'articulated_lorry', keywords: ['vrachtwagen'] },
      { emoji: '🚜', name: 'tractor', keywords: ['tractor'] },
      { emoji: '🚲', name: 'bicycle', keywords: ['fiets'] },
      { emoji: '🛵', name: 'motor_scooter', keywords: ['scooter'] },
      { emoji: '🏍️', name: 'motorcycle', keywords: ['motor'] },
      { emoji: '🛺', name: 'auto_rickshaw', keywords: ['tuktuk'] },
      { emoji: '🚨', name: 'rotating_light', keywords: ['zwaailicht'] },
      { emoji: '🛳️', name: 'passenger_ship', keywords: ['boot'] },
      { emoji: '⛴️', name: 'ferry', keywords: ['veerboot'] },
      { emoji: '🚤', name: 'speedboat', keywords: ['speedboot'] },
      { emoji: '🚢', name: 'ship', keywords: ['schip'] },
      { emoji: '✈️', name: 'airplane', keywords: ['vliegtuig'] },
      { emoji: '🛩️', name: 'small_airplane', keywords: ['vliegtuig'] },
      { emoji: '🛫', name: 'airplane_departure', keywords: ['vertrek'] },
      { emoji: '🛬', name: 'airplane_arrival', keywords: ['aankomst'] },
      { emoji: '🚁', name: 'helicopter', keywords: ['helicopter'] },
      { emoji: '🚀', name: 'rocket', keywords: ['raket'] },
      { emoji: '🛸', name: 'ufo', keywords: ['ufo'] },
      { emoji: '🛰️', name: 'satellite', keywords: ['satelliet'] },
    ]
  },
  {
    id: 'objects',
    name: 'Objecten',
    icon: '💡',
    emojis: [
      { emoji: '⌚', name: 'watch', keywords: ['horloge'] },
      { emoji: '📱', name: 'iphone', keywords: ['telefoon'] },
      { emoji: '📲', name: 'phone_with_arrow', keywords: ['telefoon'] },
      { emoji: '💻', name: 'laptop', keywords: ['computer'] },
      { emoji: '⌨️', name: 'keyboard', keywords: ['toetsenbord'] },
      { emoji: '🖥️', name: 'desktop_computer', keywords: ['pc'] },
      { emoji: '🖨️', name: 'printer', keywords: ['printer'] },
      { emoji: '🖱️', name: 'computer_mouse', keywords: ['muis'] },
      { emoji: '🖲️', name: 'trackball', keywords: ['muis'] },
      { emoji: '🕹️', name: 'joystick', keywords: ['games'] },
      { emoji: '🗜️', name: 'clamp', keywords: ['klem'] },
      { emoji: '💽', name: 'minidisc', keywords: ['disc'] },
      { emoji: '💾', name: 'floppy_disk', keywords: ['save'] },
      { emoji: '💿', name: 'cd', keywords: ['disk'] },
      { emoji: '📀', name: 'dvd', keywords: ['film'] },
      { emoji: '🎥', name: 'movie_camera', keywords: ['film'] },
      { emoji: '🎞️', name: 'film_frames', keywords: ['film'] },
      { emoji: '📽️', name: 'film_projector', keywords: ['bioscoop'] },
      { emoji: '📺', name: 'tv', keywords: ['televisie'] },
      { emoji: '📷', name: 'camera', keywords: ['foto'] },
      { emoji: '📸', name: 'camera_with_flash', keywords: ['foto'] },
      { emoji: '📹', name: 'video_camera', keywords: ['video'] },
      { emoji: '📼', name: 'vhs', keywords: ['video'] },
      { emoji: '🔍', name: 'mag', keywords: ['zoeken'] },
      { emoji: '🔎', name: 'mag_right', keywords: ['zoeken'] },
      { emoji: '🕯️', name: 'candle', keywords: ['kaars'] },
      { emoji: '💡', name: 'bulb', keywords: ['lamp', 'idee'] },
      { emoji: '🔦', name: 'flashlight', keywords: ['lamp'] },
      { emoji: '🏮', name: 'izakaya_lantern', keywords: ['lamp'] },
      { emoji: '📔', name: 'notebook_with_decorative_cover', keywords: ['boek'] },
      { emoji: '📕', name: 'closed_book', keywords: ['boek'] },
      { emoji: '📖', name: 'book', keywords: ['lezen'] },
      { emoji: '📗', name: 'green_book', keywords: ['boek'] },
      { emoji: '📘', name: 'blue_book', keywords: ['boek'] },
      { emoji: '📙', name: 'orange_book', keywords: ['boek'] },
      { emoji: '📚', name: 'books', keywords: ['boeken'] },
      { emoji: '📓', name: 'notebook', keywords: ['notitie'] },
      { emoji: '📒', name: 'ledger', keywords: ['notitie'] },
      { emoji: '📜', name: 'scroll', keywords: ['papier'] },
      { emoji: '📝', name: 'memo', keywords: ['notitie'] },
      { emoji: '📂', name: 'open_file_folder', keywords: ['map'] },
      { emoji: '📅', name: 'calendar', keywords: ['datum'] },
      { emoji: '📆', name: 'date', keywords: ['datum'] },
      { emoji: '🗒️', name: 'spiral_notepad', keywords: ['notitie'] },
      { emoji: '🗓️', name: 'spiral_calendar', keywords: ['datum'] },
      { emoji: '📇', name: 'card_index', keywords: ['index'] },
      { emoji: '📊', name: 'chart_with_upwards_trend', keywords: ['grafiek'] },
      { emoji: '📈', name: 'chart_with_upwards_trend', keywords: ['stijging'] },
      { emoji: '📉', name: 'chart_with_downwards_trend', keywords: ['daling'] },
      { emoji: '🗒️', name: 'spiral_notepad', keywords: ['notitie'] },
      { emoji: '🗞️', name: 'newspaper', keywords: ['krant'] },
      { emoji: '📓', name: 'notebook', keywords: ['notitie'] },
      { emoji: '📁', name: 'file_folder', keywords: ['map'] },
      { emoji: '🗂️', name: 'card_index_dividers', keywords: ['index'] },
      { emoji: '📑', name: 'bookmark_tabs', keywords: ['bladwijzer'] },
      { emoji: '🖇️', name: 'linked_paperclips', keywords: ['paperclip'] },
      { emoji: '📎', name: 'paperclip', keywords: ['paperclip'] },
      { emoji: '📍', name: 'round_pushpin', keywords: ['prikbord'] },
      { emoji: '📌', name: 'pushpin', keywords: ['prikbord'] },
      { emoji: '📏', name: 'straight_ruler', keywords: ['lineaal'] },
      { emoji: '📐', name: 'triangular_ruler', keywords: ['geodriehoek'] },
      { emoji: '✂️', name: 'scissors', keywords: ['schaar'] },
      { emoji: '🔒', name: 'lock', keywords: ['slot'] },
      { emoji: '🔓', name: 'unlock', keywords: ['open'] },
      { emoji: '🔏', name: 'lock_with_ink_pen', keywords: ['slot'] },
      { emoji: '🔐', name: 'closed_lock_with_key', keywords: ['slot'] },
      { emoji: '🔑', name: 'key', keywords: ['sleutel'] },
      { emoji: '🗝️', name: 'old_key', keywords: ['sleutel'] },
      { emoji: '🔨', name: 'hammer', keywords: ['hamer'] },
      { emoji: '🪓', name: 'axe', keywords: ['bijl'] },
      { emoji: '⛏️', name: 'pick', keywords: ['picken'] },
      { emoji: '⚒️', name: 'hammer_and_pick', keywords: ['gereedschap'] },
      { emoji: '🛠️', name: 'hammer_and_wrench', keywords: ['gereedschap'] },
      { emoji: '🗡️', name: 'dagger', keywords: ['mes'] },
      { emoji: '⚔️', name: 'swords', keywords: ['zwaarden'] },
      { emoji: '🔫', name: 'gun', keywords: ['pistool'] },
      { emoji: '🛡️', name: 'shield', keywords: ['schild'] },
      { emoji: '🔧', name: 'wrench', keywords: ['sleutel'] },
      { emoji: '🔩', name: 'nut_and_bolt', keywords: ['bout'] },
      { emoji: '⚙️', name: 'gear', keywords: ['instellingen'] },
      { emoji: '🧱', name: 'brick', keywords: ['steen'] },
      { emoji: '⛓️', name: 'chains', keywords: ['ketting'] },
      { emoji: '🧰', name: 'toolbox', keywords: ['gereedschap'] },
      { emoji: '🧲', name: 'magnet', keywords: ['magneet'] },
      { emoji: '🧼', name: 'soap', keywords: ['zeep'] },
      { emoji: '🪽', name: 'wing', keywords: ['vleugel'] },
      { emoji: '🧳', name: 'luggage', keywords: ['koffer'] },
      { emoji: '🚿', name: 'shower', keywords: ['douche'] },
      { emoji: '🛀', name: 'bath', keywords: ['bad'] },
      { emoji: '🛁', name: 'bathtub', keywords: ['bad'] },
      { emoji: '🚽', name: 'toilet', keywords: ['wc'] },
      { emoji: '🪠', name: 'plunger', keywords: ['ontstopper'] },
      { emoji: '🧴', name: 'lotion', keywords: ['zalf'] },
      { emoji: '🧹', name: 'broom', keywords: ['bezem'] },
      { emoji: '🧺', name: 'basket', keywords: ['mand'] },
      { emoji: '🧻', name: 'toilet_paper', keywords: ['wc_papier'] },
      { emoji: '🧼', name: 'soap', keywords: ['zeep'] },
      { emoji: '🪒', name: 'razor', keywords: ['scheermes'] },
      { emoji: '🧸', name: 'teddy_bear', keywords: ['beer'] },
      { emoji: '🪑', name: 'chair', keywords: ['stoel'] },
      { emoji: '🧹', name: 'broom', keywords: ['bezem'] },
      { emoji: '🧺', name: 'basket', keywords: ['mand'] },
      { emoji: '🧼', name: 'soap', keywords: ['zeep'] },
      { emoji: '🧻', name: 'toilet_paper', keywords: ['wc_papier'] },
    ]
  },
  {
    id: 'symbols',
    name: 'Symbolen',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', name: 'heart', keywords: ['liefde', 'love'] },
      { emoji: '🧡', name: 'orange_heart', keywords: ['liefde'] },
      { emoji: '💛', name: 'yellow_heart', keywords: ['liefde'] },
      { emoji: '💚', name: 'green_heart', keywords: ['liefde'] },
      { emoji: '💙', name: 'blue_heart', keywords: ['liefde'] },
      { emoji: '💜', name: 'purple_heart', keywords: ['liefde'] },
      { emoji: '🖤', name: 'black_heart', keywords: ['liefde'] },
      { emoji: '🤍', name: 'white_heart', keywords: ['liefde'] },
      { emoji: '🤎', name: 'brown_heart', keywords: ['liefde'] },
      { emoji: '💔', name: 'broken_heart', keywords: ['gebroken'] },
      { emoji: '❣️', name: 'heart_exclamation', keywords: ['liefde'] },
      { emoji: '💕', name: 'two_hearts', keywords: ['liefde'] },
      { emoji: '💞', name: 'revolving_hearts', keywords: ['liefde'] },
      { emoji: '💓', name: 'beating_heart', keywords: ['liefde'] },
      { emoji: '💗', name: 'growing_heart', keywords: ['liefde'] },
      { emoji: '💖', name: 'sparkling_heart', keywords: ['liefde'] },
      { emoji: '💘', name: 'cupid', keywords: ['liefde'] },
      { emoji: '💝', name: 'gift_heart', keywords: ['liefde'] },
      { emoji: '💟', name: 'heart_decoration', keywords: ['liefde'] },
      { emoji: '💯', name: '100', keywords: ['perfect'] },
      { emoji: '💢', name: 'anger', keywords: ['boos'] },
      { emoji: '💥', name: 'boom', keywords: ['knal'] },
      { emoji: '💫', name: 'dizzy', keywords: ['sterren'] },
      { emoji: '💦', name: 'sweat_drops', keywords: ['water'] },
      { emoji: '💨', name: 'dash', keywords: ['wind'] },
      { emoji: '🕳️', name: 'hole', keywords: ['gat'] },
      { emoji: '💣', name: 'bomb', keywords: ['bom'] },
      { emoji: '💬', name: 'speech_balloon', keywords: ['praten'] },
      { emoji: '🗯️', name: 'right_anger_bubble', keywords: ['boos'] },
      { emoji: '💭', name: 'thought_balloon', keywords: ['denken'] },
      { emoji: '💤', name: 'zzz', keywords: ['slaap'] },
      { emoji: '➕', name: 'plus', keywords: ['plus'] },
      { emoji: '➖', name: 'minus', keywords: ['min'] },
      { emoji: '✖️', name: 'multiply', keywords: ['keer'] },
      { emoji: '➕', name: 'plus', keywords: ['plus'] },
      { emoji: '♾️', name: 'infinity', keywords: ['oneindig'] },
      { emoji: '‼️', name: 'bangbang', keywords: ['pas_op'] },
      { emoji: '⁉️', name: 'interrobang', keywords: ['vraag'] },
      { emoji: '❓', name: 'question', keywords: ['vraag'] },
      { emoji: '❔', name: 'grey_question', keywords: ['vraag'] },
      { emoji: '❕', name: 'grey_exclamation', keywords: ['uitroepteken'] },
      { emoji: '❗', name: 'exclamation', keywords: ['uitroepteken'] },
      { emoji: '⭕', name: 'o', keywords: ['cirkel'] },
      { emoji: '❌', name: 'x', keywords: ['nee'] },
      { emoji: '✅', name: 'white_check_mark', keywords: ['ja'] },
      { emoji: '✳️', name: 'eight_spoked_asterisk', keywords: ['ster'] },
      { emoji: '✴️', name: 'eight_pointed_black_star', keywords: ['ster'] },
      { emoji: '❇️', name: 'sparkle', keywords: ['mooi'] },
      { emoji: '〽️', name: 'part_alternation_mark', keywords: ['symbol'] },
      { emoji: '⚠️', name: 'warning', keywords: ['gevaar'] },
      { emoji: '🚩', name: 'triangular_flag_on_post', keywords: ['vlag'] },
      { emoji: '🔥', name: 'fire', keywords: ['heet'] },
      { emoji: '✨', name: 'sparkles', keywords: ['mooi'] },
    ]
  }
];
