export const NEWS_ITEMS = [
  {
    id: 6,
    title: "Nieuwe Gebruiksvoorwaarden (ToS)",
    content: "We hebben onze Gebruiksvoorwaarden bijgewerkt. Belangrijk om te weten: de eigenaar is niet verantwoordelijk voor het gedrag of de uitingen van gebruikers op dit platform. Elke gebruiker draagt zelf de volledige verantwoordelijkheid voor hun acties en geplaatste inhoud. Lees de volledige voorwaarden op de voorpagina.",
    date: "2026-04-15",
    category: "Juridisch"
  },
  {
    id: 5,
    title: "FTJM Forum Update v1.7.9.6",
    content: "In deze update hebben we de synchronisatie van geluidsinstellingen verbeterd. Oude instellingen worden nu automatisch opgeschoond en gemigreerd naar het nieuwe formaat om conflicten te voorkomen. Ook zijn de standaard geluiden bijgewerkt naar de nieuwe image2url links.",
    date: "2026-04-14",
    category: "Update"
  },
  {
    id: 4,
    title: "FTJM Forum Update v1.7.9.05",
    content: "In deze tussentijdse update hebben we diverse kritieke bugs opgelost die door de community zijn gemeld. Fixes: [MSG-01] Profielfoto's in chat header laden nu correct. [NOT-02] Meldingen voor gemiste berichten worden nu correct weergegeven. [UI-05] Dropdown menu z-index bug opgelost. [SYS-08] Berichtenlijst synchronisatie verbeterd. [NAV-03] Nieuwe visuele indicators voor menu en nieuws toegevoegd.",
    date: "2026-04-11",
    category: "Update"
  },
  {
    id: 1,
    title: "FTJM Forum Update v1.7.9",
    content: "We hebben zojuist versie 1.7.9 uitgerold. In deze update hebben we het rapportage-systeem verbeterd, de beveiliging aangescherpt met menselijke verificatie en diverse bugfixes doorgevoerd voor een stabielere ervaring.",
    date: "2026-04-10",
    category: "Update"
  },
  {
    id: 2,
    title: "Nieuwe Huisregels",
    content: "Zorg ervoor dat je de bijgewerkte huisregels leest in de instellingen sectie om een veilige omgeving voor iedereen te behouden.",
    date: "2026-04-07",
    category: "Aankondiging"
  },
  {
    id: 3,
    title: "Community Spotlight",
    content: "Deze week zetten we onze meest actieve forumleden in het zonnetje. Bedankt voor jullie waardevolle bijdragen!",
    date: "2026-04-05",
    category: "Community"
  }
];

export const SOUND_OPTIONS = [
  { name: 'Ping (Default)', url: 'https://image2url.com/r2/default/audio/1775756671546-6f36bf87-4347-477b-a2da-1af03009fdcf.mp3' },
  { name: 'Notification', url: 'https://image2url.com/r2/default/audio/1775755636867-f3aa78d1-03e7-48c2-b75a-a5f990f517e9.mp3' },
  { name: 'Chime', url: 'https://image2url.com/r2/default/audio/1775756302748-a840da24-e9d3-47a0-9e14-2a582fc0e093.mp3' },
  { name: 'Alert', url: 'https://image2url.com/r2/default/audio/1775754319337-0525bbd3-8adb-4c26-ae70-842ba5769e7f.wav' },
  { name: 'Pop', url: 'https://image2url.com/r2/default/audio/1775755973661-157bd979-8f6e-4d86-9e32-74761db166d9.mp3' },
  { name: 'Success', url: 'https://assets.mixkit.co/active_storage/sfx/2366/2366-preview.mp3' },
  { name: 'Bling', url: 'https://assets.mixkit.co/active_storage/sfx/2372/2372-preview.mp3' },
  { name: 'Standaard (Old)', url: 'https://assets.mixkit.co/active_storage/sfx/2354/2354-preview.mp3' },
  { name: 'Melding (Old)', url: 'https://assets.mixkit.co/active_storage/sfx/2358/2358-preview.mp3' },
];

export const PATTERNS = [
  { id: 'none', name: 'Geen', style: '' },
  { id: 'dots', name: 'Stippen', style: 'radial-gradient(var(--custom-accent) 1px, transparent 1px)', size: '20px 20px' },
  { id: 'grid', name: 'Raster', style: 'linear-gradient(var(--custom-accent) 1px, transparent 1px), linear-gradient(90deg, var(--custom-accent) 1px, transparent 1px)', size: '20px 20px' },
  { id: 'stripes', name: 'Strepen', style: 'linear-gradient(45deg, var(--custom-accent) 25%, transparent 25%, transparent 50%, var(--custom-accent) 50%, var(--custom-accent) 75%, transparent 75%, transparent)', size: '20px 20px' },
  { id: 'waves', name: 'Golven', style: 'radial-gradient(circle at 100% 50%, transparent 20%, var(--custom-accent) 21%, var(--custom-accent) 34%, transparent 35%, transparent), radial-gradient(circle at 0% 50%, transparent 20%, var(--custom-accent) 21%, var(--custom-accent) 34%, transparent 35%, transparent)', size: '40px 40px' },
  { id: 'diagonal', name: 'Diagonaal', style: 'repeating-linear-gradient(45deg, transparent, transparent 10px, var(--custom-accent) 10px, var(--custom-accent) 11px)', size: 'auto' },
];

export const EMOJI_LIST = [
  { emoji: '😀', name: 'smile', keywords: ['happy', 'smile', 'blij', ':D', ':-D'] },
  { emoji: '😆', name: 'laughing', keywords: ['happy', 'laugh', 'lachen', 'XD', 'xD', 'xd'] },
  { emoji: '😂', name: 'joy', keywords: ['laugh', 'lachen', 'huilen'] },
  { emoji: '🤣', name: 'rofl', keywords: ['rolling', 'lachen'] },
  { emoji: '😊', name: 'blush', keywords: ['smile', 'blij'] },
  { emoji: '🙂', name: 'slight_smile', keywords: ['smile', 'blij', ':)', ':-)'] },
  { emoji: '😉', name: 'wink', keywords: ['wink', 'knipoog', ';)', ';-)'] },
  { emoji: '😍', name: 'heart_eyes', keywords: ['love', 'verliefd'] },
  { emoji: '🥰', name: 'smiling_face_with_hearts', keywords: ['love', 'verliefd'] },
  { emoji: '😘', name: 'kissing_heart', keywords: ['kiss', 'kus', ':*', ':-*'] },
  { emoji: '😜', name: 'stuck_out_tongue_winking_eye', keywords: ['wink', 'tongue', 'gekkie'] },
  { emoji: '😎', name: 'sunglasses', keywords: ['cool', 'stoer', 'B)', 'B-)'] },
  { emoji: '🤔', name: 'thinking', keywords: ['think', 'nadenken'] },
  { emoji: '🤨', name: 'raised_eyebrow', keywords: ['sus', 'hmmm'] },
  { emoji: '😐', name: 'neutral_face', keywords: ['meh', 'neutraal', ':|', ':-|'] },
  { emoji: '😑', name: 'expressionless', keywords: ['meh'] },
  { emoji: '😶', name: 'no_mouth', keywords: ['stil'] },
  { emoji: '🙄', name: 'roll_eyes', keywords: ['roll', 'zucht'] },
  { emoji: '😏', name: 'smirk', keywords: ['smirk', 'grijns'] },
  { emoji: '😣', name: 'persevere', keywords: ['pijn'] },
  { emoji: '😥', name: 'sad_but_relieved', keywords: ['sad', 'opgelucht'] },
  { emoji: '😮', name: 'open_mouth', keywords: ['wow', 'verbaasd', ':O', ':o', ':-O', ':-o'] },
  { emoji: '🤐', name: 'zipper_mouth', keywords: ['stil', 'geheim'] },
  { emoji: '😯', name: 'hushed', keywords: ['wow'] },
  { emoji: '😪', name: 'sleepy', keywords: ['slaap'] },
  { emoji: '😫', name: 'tired_face', keywords: ['moe'] },
  { emoji: '🥱', name: 'yawning_face', keywords: ['gaap'] },
  { emoji: '😴', name: 'sleeping', keywords: ['slaap'] },
  { emoji: '😌', name: 'relieved', keywords: ['fijn'] },
  { emoji: '😛', name: 'stuck_out_tongue', keywords: ['tongue', 'tong', ':P', ':p', ':-P', ':-p'] },
  { emoji: '😜', name: 'stuck_out_tongue_winking_eye', keywords: ['wink'] },
  { emoji: '😝', name: 'stuck_out_tongue_closed_eyes', keywords: ['laugh'] },
  { emoji: '🤤', name: 'drooling', keywords: ['lekker'] },
  { emoji: '😒', name: 'unamused', keywords: ['meh'] },
  { emoji: '😓', name: 'sweat', keywords: ['stress'] },
  { emoji: '😔', name: 'pensive', keywords: ['sad'] },
  { emoji: '😕', name: 'confused', keywords: ['verward', ':/', ':-/'] },
  { emoji: '🙃', name: 'upside_down', keywords: ['gek'] },
  { emoji: '🤑', name: 'money_mouth', keywords: ['geld'] },
  { emoji: '😲', name: 'astonished', keywords: ['wow'] },
  { emoji: '☹️', name: 'frowning', keywords: ['sad'] },
  { emoji: '🙁', name: 'slight_frown', keywords: ['sad'] },
  { emoji: '😖', name: 'confounded', keywords: ['pijn'] },
  { emoji: '😞', name: 'disappointed', keywords: ['sad'] },
  { emoji: '😟', name: 'worried', keywords: ['bang'] },
  { emoji: '😤', name: 'triumph', keywords: ['boos'] },
  { emoji: '😢', name: 'cry', keywords: ['huilen'] },
  { emoji: '😭', name: 'sob', keywords: ['huilen'] },
  { emoji: '😦', name: 'frowning_with_open_mouth', keywords: ['wow'] },
  { emoji: '😧', name: 'anguished', keywords: ['wow'] },
  { emoji: '😨', name: 'fearful', keywords: ['bang'] },
  { emoji: '😩', name: 'weary', keywords: ['moe'] },
  { emoji: '🤯', name: 'exploding_head', keywords: ['mindblown'] },
  { emoji: '😬', name: 'grimacing', keywords: ['oeps'] },
  { emoji: '😰', name: 'cold_sweat', keywords: ['bang'] },
  { emoji: '😱', name: 'scream', keywords: ['bang'] },
  { emoji: '🥵', name: 'hot_face', keywords: ['heet'] },
  { emoji: '🥶', name: 'cold_face', keywords: ['koud'] },
  { emoji: '😳', name: 'flushed', keywords: ['bloos', ':$', ':-$'] },
  { emoji: '🤪', name: 'zany_face', keywords: ['gek'] },
  { emoji: '😵', name: 'dizzy_face', keywords: ['duizelig'] },
  { emoji: '😡', name: 'rage', keywords: ['boos'] },
  { emoji: '😠', name: 'angry', keywords: ['boos'] },
  { emoji: '🤬', name: 'cursing', keywords: ['boos'] },
  { emoji: '😷', name: 'mask', keywords: ['ziek'] },
  { emoji: '🤒', name: 'thermometer', keywords: ['ziek'] },
  { emoji: '🤕', name: 'bandage', keywords: ['ziek'] },
  { emoji: '🤢', name: 'nauseated', keywords: ['vies'] },
  { emoji: '🤮', name: 'vomiting', keywords: ['vies'] },
  { emoji: '🤧', name: 'sneezing', keywords: ['ziek'] },
  { emoji: '😇', name: 'halo', keywords: ['engel'] },
  { emoji: '🤠', name: 'cowboy', keywords: ['cowboy'] },
  { emoji: '🤡', name: 'clown', keywords: ['clown'] },
  { emoji: '🥳', name: 'party', keywords: ['feest'] },
  { emoji: '🥴', name: 'woozy', keywords: ['dronken'] },
  { emoji: '🥺', name: 'pleading', keywords: ['lief'] },
  { emoji: '🤥', name: 'lying', keywords: ['leugen'] },
  { emoji: '🤫', name: 'shushing', keywords: ['stil'] },
  { emoji: '🤭', name: 'hand_over_mouth', keywords: ['oeps'] },
  { emoji: '🧐', name: 'monocle', keywords: ['slim'] },
  { emoji: '🤓', name: 'nerd', keywords: ['nerd'] },
  { emoji: '😈', name: 'smiling_imp', keywords: ['duivel'] },
  { emoji: '👿', name: 'imp', keywords: ['duivel'] },
  { emoji: '👹', name: 'ogre', keywords: ['monster'] },
  { emoji: '👺', name: 'goblin', keywords: ['monster'] },
  { emoji: '💀', name: 'skull', keywords: ['dood'] },
  { emoji: '👻', name: 'ghost', keywords: ['geest'] },
  { emoji: '👽', name: 'alien', keywords: ['alien'] },
  { emoji: '🤖', name: 'robot', keywords: ['robot'] },
  { emoji: '💩', name: 'poop', keywords: ['poep'] },
  { emoji: '😺', name: 'smiley_cat', keywords: ['kat'] },
  { emoji: '😸', name: 'smile_cat', keywords: ['kat'] },
  { emoji: '😻', name: 'heart_eyes_cat', keywords: ['kat'] },
  { emoji: '😽', name: 'kissing_cat', keywords: ['kat'] },
  { emoji: '🙀', name: 'scream_cat', keywords: ['kat'] },
  { emoji: '😿', name: 'crying_cat', keywords: ['kat'] },
  { emoji: '😹', name: 'joy_cat', keywords: ['kat'] },
  { emoji: '😾', name: 'pouting_cat', keywords: ['kat'] },
  { emoji: '🤲', name: 'palms_up', keywords: ['gebed'] },
  { emoji: '👐', name: 'open_hands', keywords: ['open'] },
  { emoji: '🙌', name: 'raised_hands', keywords: ['feest'] },
  { emoji: '👏', name: 'clapping', keywords: ['klappen'] },
  { emoji: '🤝', name: 'handshake', keywords: ['deal'] },
  { emoji: '👍', name: '+1', keywords: ['goed'] },
  { emoji: '👎', name: '-1', keywords: ['slecht'] },
  { emoji: '👊', name: 'fist', keywords: ['boks'] },
  { emoji: '✊', name: 'fist_raised', keywords: ['power'] },
  { emoji: '🤛', name: 'fist_left', keywords: ['boks'] },
  { emoji: '🤜', name: 'fist_right', keywords: ['boks'] },
  { emoji: '🤞', name: 'fingers_crossed', keywords: ['hoop'] },
  { emoji: '✌️', name: 'v', keywords: ['peace'] },
  { emoji: '🤟', name: 'love_you', keywords: ['love'] },
  { emoji: '🤘', name: 'metal', keywords: ['rock'] },
  { emoji: '👌', name: 'ok_hand', keywords: ['ok'] },
  { emoji: '👈', name: 'point_left', keywords: ['links'] },
  { emoji: '👉', name: 'point_right', keywords: ['rechts'] },
  { emoji: '👆', name: 'point_up', keywords: ['boven'] },
  { emoji: '👇', name: 'point_down', keywords: ['onder'] },
  { emoji: '☝️', name: 'point_up_2', keywords: ['boven'] },
  { emoji: '✋', name: 'hand', keywords: ['stop'] },
  { emoji: '🤚', name: 'raised_back_of_hand', keywords: ['stop'] },
  { emoji: '🖐️', name: 'hand_splayed', keywords: ['stop'] },
  { emoji: '🖖', name: 'vulcan', keywords: ['spock'] },
  { emoji: '👋', name: 'wave', keywords: ['zwaaien'] },
  { emoji: '🤙', name: 'call_me', keywords: ['bellen'] },
  { emoji: '💪', name: 'muscle', keywords: ['sterk'] },
  { emoji: '🖕', name: 'middle_finger', keywords: ['middelvinger'] },
  { emoji: '✍️', name: 'writing_hand', keywords: ['schrijven'] },
  { emoji: '🙏', name: 'pray', keywords: ['bidden'] },
  { emoji: '💍', name: 'ring', keywords: ['trouwen'] },
  { emoji: '💄', name: 'lipstick', keywords: ['makeup'] },
  { emoji: '💋', name: 'kiss', keywords: ['kus'] },
  { emoji: '👄', name: 'lips', keywords: ['mond'] },
  { emoji: '👅', name: 'tongue', keywords: ['tong'] },
  { emoji: '👂', name: 'ear', keywords: ['oor'] },
  { emoji: '👃', name: 'nose', keywords: ['neus'] },
  { emoji: '👣', name: 'feet', keywords: ['voeten'] },
  { emoji: '👁️', name: 'eye', keywords: ['oog'] },
  { emoji: '👀', name: 'eyes', keywords: ['ogen'] },
  { emoji: '🧠', name: 'brain', keywords: ['hersenen'] },
  { emoji: '🗣️', name: 'speaking_head', keywords: ['praten'] },
  { emoji: '👤', name: 'bust_in_silhouette', keywords: ['persoon'] },
  { emoji: '👥', name: 'busts_in_silhouette', keywords: ['mensen'] },
  { emoji: '👶', name: 'baby', keywords: ['baby'] },
  { emoji: '👧', name: 'girl', keywords: ['meisje'] },
  { emoji: '🧒', name: 'child', keywords: ['kind'] },
  { emoji: '👦', name: 'boy', keywords: ['jongen'] },
  { emoji: '👩', name: 'woman', keywords: ['vrouw'] },
  { emoji: '🧑', name: 'person', keywords: ['persoon'] },
  { emoji: '👨', name: 'man', keywords: ['man'] },
  { emoji: '👱', name: 'blond_person', keywords: ['blond'] },
  { emoji: '🧔', name: 'bearded_person', keywords: ['baard'] },
  { emoji: '👵', name: 'old_woman', keywords: ['oma'] },
  { emoji: '🧓', name: 'older_person', keywords: ['oud'] },
  { emoji: '👴', name: 'old_man', keywords: ['opa'] },
  { emoji: '👲', name: 'man_with_gua_pi_mao', keywords: ['hoed'] },
  { emoji: '👳', name: 'turban_person', keywords: ['tulband'] },
  { emoji: '🧕', name: 'woman_with_headscarf', keywords: ['hoofddoek'] },
  { emoji: '👮', name: 'police_officer', keywords: ['politie'] },
  { emoji: '👷', name: 'construction_worker', keywords: ['bouw'] },
  { emoji: '💂', name: 'guard', keywords: ['bewaker'] },
  { emoji: '🕵️', name: 'detective', keywords: ['detective'] },
  { emoji: '👩‍⚕️', name: 'woman_health_worker', keywords: ['dokter'] },
  { emoji: '👨‍⚕️', name: 'man_health_worker', keywords: ['dokter'] },
  { emoji: '👩‍🌾', name: 'woman_farmer', keywords: ['boer'] },
  { emoji: '👨‍🌾', name: 'man_farmer', keywords: ['boer'] },
  { emoji: '👩‍🍳', name: 'woman_cook', keywords: ['kok'] },
  { emoji: '👨‍🍳', name: 'man_cook', keywords: ['kok'] },
  { emoji: '👩‍🎓', name: 'woman_student', keywords: ['student'] },
  { emoji: '👨‍🎓', name: 'man_student', keywords: ['student'] },
  { emoji: '👩‍🎤', name: 'woman_singer', keywords: ['zanger'] },
  { emoji: '👨‍🎤', name: 'man_singer', keywords: ['zanger'] },
  { emoji: '👩‍🏫', name: 'woman_teacher', keywords: ['leraar'] },
  { emoji: '👨‍🏫', name: 'man_teacher', keywords: ['leraar'] },
  { emoji: '👩‍🏭', name: 'woman_factory_worker', keywords: ['fabriek'] },
  { emoji: '👨‍🏭', name: 'man_factory_worker', keywords: ['fabriek'] },
  { emoji: '👩‍💻', name: 'woman_technologist', keywords: ['laptop'] },
  { emoji: '👨‍💻', name: 'man_technologist', keywords: ['laptop'] },
  { emoji: '👩‍💼', name: 'woman_office_worker', keywords: ['kantoor'] },
  { emoji: '👨‍💼', name: 'man_office_worker', keywords: ['kantoor'] },
  { emoji: '👩‍🔧', name: 'woman_mechanic', keywords: ['monteur'] },
  { emoji: '👨‍🔧', name: 'man_mechanic', keywords: ['monteur'] },
  { emoji: '👩‍🔬', name: 'woman_scientist', keywords: ['wetenschap'] },
  { emoji: '👨‍🔬', name: 'man_scientist', keywords: ['wetenschap'] },
  { emoji: '👩‍🎨', name: 'woman_artist', keywords: ['kunst'] },
  { emoji: '👨‍🎨', name: 'man_artist', keywords: ['kunst'] },
  { emoji: '👩‍🚒', name: 'woman_firefighter', keywords: ['brandweer'] },
  { emoji: '👨‍🚒', name: 'man_firefighter', keywords: ['brandweer'] },
  { emoji: '👩‍✈️', name: 'woman_pilot', keywords: ['piloot'] },
  { emoji: '👨‍✈️', name: 'man_pilot', keywords: ['piloot'] },
  { emoji: '👩‍🚀', name: 'woman_astronaut', keywords: ['ruimte'] },
  { emoji: '👨‍🚀', name: 'man_astronaut', keywords: ['ruimte'] },
  { emoji: '👩‍⚖️', name: 'woman_judge', keywords: ['rechter'] },
  { emoji: '👨‍⚖️', name: 'man_judge', keywords: ['rechter'] },
  { emoji: '👰', name: 'bride_with_veil', keywords: ['bruid'] },
  { emoji: '🤵', name: 'man_in_tuxedo', keywords: ['bruidegom'] },
  { emoji: '👸', name: 'princess', keywords: ['prinses'] },
  { emoji: '🤴', name: 'prince', keywords: ['prins'] },
  { emoji: '🤶', name: 'mrs_claus', keywords: ['kerst'] },
  { emoji: '🎅', name: 'santa', keywords: ['kerst'] },
  { emoji: '🧙', name: 'mage', keywords: ['tovenaar'] },
  { emoji: '🧚', name: 'fairy', keywords: ['fee'] },
  { emoji: '🧛', name: 'vampire', keywords: ['vampier'] },
  { emoji: '🧜', name: 'merperson', keywords: ['zeemeermin'] },
  { emoji: '🧝', name: 'elf', keywords: ['elf'] },
  { emoji: '🧞', name: 'genie', keywords: ['geest'] },
  { emoji: '🧟', name: 'zombie', keywords: ['zombie'] },
  { emoji: '💆', name: 'person_getting_massage', keywords: ['massage'] },
  { emoji: '💇', name: 'person_getting_haircut', keywords: ['kapper'] },
  { emoji: '🚶', name: 'person_walking', keywords: ['lopen'] },
  { emoji: '🏃', name: 'person_running', keywords: ['rennen'] },
  { emoji: '💃', name: 'woman_dancing', keywords: ['dansen'] },
  { emoji: '🕺', name: 'man_dancing', keywords: ['dansen'] },
  { emoji: '👯', name: 'people_with_bunny_ears', keywords: ['feest'] },
  { emoji: '🧖', name: 'person_in_steamy_room', keywords: ['sauna'] },
  { emoji: '🧗', name: 'person_climbing', keywords: ['klimmen'] },
  { emoji: '🧘', name: 'person_in_lotus_position', keywords: ['yoga'] },
  { emoji: '🛀', name: 'person_taking_bath', keywords: ['bad'] },
  { emoji: '🛌', name: 'person_in_bed', keywords: ['bed'] },
  { emoji: '🕴️', name: 'man_in_business_suit_levitating', keywords: ['pak'] },
  { emoji: '🏇', name: 'horse_racing', keywords: ['paard'] },
  { emoji: '⛷️', name: 'skier', keywords: ['ski'] },
  { emoji: '🏂', name: 'snowboarder', keywords: ['snowboard'] },
  { emoji: '🏌️', name: 'golfer', keywords: ['golf'] },
  { emoji: '🏄', name: 'surfer', keywords: ['surfen'] },
  { emoji: '🚣', name: 'person_rowing_boat', keywords: ['roeien'] },
  { emoji: '🏊', name: 'person_swimming', keywords: ['zwemmen'] },
  { emoji: '⛹️', name: 'person_with_ball', keywords: ['basketbal'] },
  { emoji: '🏋️', name: 'person_lifting_weights', keywords: ['fitness'] },
  { emoji: '🚴', name: 'person_biking', keywords: ['fietsen'] },
  { emoji: '🚵', name: 'person_mountain_biking', keywords: ['fietsen'] },
  { emoji: '🤸', name: 'person_cartwheeling', keywords: ['turnen'] },
  { emoji: '🤼', name: 'people_wrestling', keywords: ['worstelen'] },
  { emoji: '🤽', name: 'person_playing_water_polo', keywords: ['waterpolo'] },
  { emoji: '🤾', name: 'person_playing_handball', keywords: ['handbal'] },
  { emoji: '🤹', name: 'person_juggling', keywords: ['jongleren'] },
  { emoji: '👫', name: 'man_and_woman_holding_hands', keywords: ['stel'] },
  { emoji: '👬', name: 'two_men_holding_hands', keywords: ['stel'] },
  { emoji: '👭', name: 'two_women_holding_hands', keywords: ['stel'] },
  { emoji: '💏', name: 'kiss_couple', keywords: ['kus'] },
  { emoji: '💑', name: 'couple_with_heart', keywords: ['liefde'] },
  { emoji: '👪', name: 'family', keywords: ['gezin'] },
  { emoji: '🤳', name: 'selfie', keywords: ['selfie'] },
  { emoji: '💪', name: 'muscle', keywords: ['sterk'] },
  { emoji: '👈', name: 'point_left', keywords: ['links'] },
  { emoji: '👉', name: 'point_right', keywords: ['rechts'] },
  { emoji: '☝️', name: 'point_up', keywords: ['boven'] },
  { emoji: '👆', name: 'point_up_2', keywords: ['boven'] },
  { emoji: '🖕', name: 'middle_finger', keywords: ['middelvinger'] },
  { emoji: '👇', name: 'point_down', keywords: ['onder'] },
  { emoji: '✌️', name: 'v', keywords: ['peace'] },
  { emoji: '🤞', name: 'fingers_crossed', keywords: ['hoop'] },
  { emoji: '🖖', name: 'vulcan', keywords: ['spock'] },
  { emoji: '🤘', name: 'metal', keywords: ['rock'] },
  { emoji: '🤙', name: 'call_me', keywords: ['bellen'] },
  { emoji: '🖐️', name: 'hand_splayed', keywords: ['stop'] },
  { emoji: '✋', name: 'hand', keywords: ['stop'] },
  { emoji: '👌', name: 'ok_hand', keywords: ['ok'] },
  { emoji: '👍', name: '+1', keywords: ['goed'] },
  { emoji: '👎', name: '-1', keywords: ['slecht'] },
  { emoji: '✊', name: 'fist_raised', keywords: ['power'] },
  { emoji: '👊', name: 'fist', keywords: ['boks'] },
  { emoji: '🤛', name: 'fist_left', keywords: ['boks'] },
  { emoji: '🤜', name: 'fist_right', keywords: ['boks'] },
  { emoji: '🤚', name: 'raised_back_of_hand', keywords: ['stop'] },
  { emoji: '👋', name: 'wave', keywords: ['zwaaien'] },
  { emoji: '🤟', name: 'love_you', keywords: ['love'] },
  { emoji: '✍️', name: 'writing_hand', keywords: ['schrijven'] },
  { emoji: '👏', name: 'clapping', keywords: ['klappen'] },
  { emoji: '👐', name: 'open_hands', keywords: ['open'] },
  { emoji: '🙌', name: 'raised_hands', keywords: ['feest'] },
  { emoji: '🤲', name: 'palms_up', keywords: ['gebed'] },
  { emoji: '🙏', name: 'pray', keywords: ['bidden'] },
  { emoji: '🤝', name: 'handshake', keywords: ['deal'] },
  { emoji: '💅', name: 'nail_polish', keywords: ['nagels'] },
  { emoji: '👂', name: 'ear', keywords: ['oor'] },
  { emoji: '👃', name: 'nose', keywords: ['neus'] },
  { emoji: '👣', name: 'feet', keywords: ['voeten'] },
  { emoji: '👀', name: 'eyes', keywords: ['ogen'] },
  { emoji: '👁️', name: 'eye', keywords: ['oog'] },
  { emoji: '👅', name: 'tongue', keywords: ['tong'] },
  { emoji: '👄', name: 'lips', keywords: ['mond'] },
  { emoji: '💋', name: 'kiss', keywords: ['kus'] },
  { emoji: '💘', name: 'cupid', keywords: ['liefde'] },
  { emoji: '💝', name: 'gift_heart', keywords: ['liefde'] },
  { emoji: '💖', name: 'sparkling_heart', keywords: ['liefde'] },
  { emoji: '💗', name: 'growing_heart', keywords: ['liefde'] },
  { emoji: '💓', name: 'beating_heart', keywords: ['liefde'] },
  { emoji: '💞', name: 'revolving_hearts', keywords: ['liefde'] },
  { emoji: '💕', name: 'two_hearts', keywords: ['liefde'] },
  { emoji: '💟', name: 'heart_decoration', keywords: ['liefde'] },
  { emoji: '❣️', name: 'heart_exclamation', keywords: ['liefde'] },
  { emoji: '💔', name: 'broken_heart', keywords: ['gebroken'] },
  { emoji: '❤️', name: 'heart', keywords: ['liefde'] },
  { emoji: '🧡', name: 'orange_heart', keywords: ['liefde'] },
  { emoji: '💛', name: 'yellow_heart', keywords: ['liefde'] },
  { emoji: '💚', name: 'green_heart', keywords: ['liefde'] },
  { emoji: '💙', name: 'blue_heart', keywords: ['liefde'] },
  { emoji: '💜', name: 'purple_heart', keywords: ['liefde'] },
  { emoji: '🖤', name: 'black_heart', keywords: ['liefde'] },
  { emoji: '🤍', name: 'white_heart', keywords: ['liefde'] },
  { emoji: '🤎', name: 'brown_heart', keywords: ['liefde'] },
  { emoji: '💯', name: '100', keywords: ['perfect'] },
  { emoji: '💢', name: 'anger', keywords: ['boos'] },
  { emoji: '💥', name: 'boom', keywords: ['knal'] },
  { emoji: '💫', name: 'dizzy', keywords: ['sterren'] },
  { emoji: '💦', name: 'sweat_drops', keywords: ['water'] },
  { emoji: '💨', name: 'dash', keywords: ['snel'] },
  { emoji: '🕳️', name: 'hole', keywords: ['gat'] },
  { emoji: '💣', name: 'bomb', keywords: ['bom'] },
  { emoji: '💬', name: 'speech_balloon', keywords: ['praten'] },
  { emoji: '👁️‍🗨️', name: 'eye_in_speech_bubble', keywords: ['oog'] },
  { emoji: '🗨️', name: 'left_speech_bubble', keywords: ['praten'] },
  { emoji: '🗯️', name: 'right_anger_bubble', keywords: ['boos'] },
  { emoji: '💭', name: 'thought_balloon', keywords: ['denken'] },
  { emoji: '💤', name: 'zzz', keywords: ['slaap'] },
];
