/**
 * Comprehensive List of Protected Identities & Anti-Piracy Names
 * Exclusively reserved for Jonatech and verified administrator Marko Hoksen.
 * Contains 170+ variations, phonetic spellings, typo-squats, and impersonation prefixes/suffixes.
 */

export const PROTECTED_NAMES_LIST: string[] = [
  // ==========================================
  // 1. MARKO VARIATIONS & PHONETICS (45+ items)
  // ==========================================
  'marko',
  'marco',
  'maarko',
  'maarco',
  'marcko',
  'markko',
  'marcco',
  'markos',
  'marcos',
  'markus',
  'marcus',
  'marckus',
  'marqo',
  'marqoo',
  'marqox',
  'markoo',
  'marcoo',
  'marccoo',
  'markkoo',
  'maric',
  'marico',
  'markox',
  'marcox',
  'marckox',
  'markoh',
  'marcoh',
  'marckoh',
  'markee',
  'markie',
  'marky',
  'mark0',
  'marc0',
  'm4rko',
  'm4rc0',
  'm@rko',
  'm@rc0',
  'markovich',
  'markovic',
  'markovski',
  'markoto',
  'markoman',
  'markotheboss',
  'markotheadmin',
  'markodev',
  'markoapp',
  'markov',
  'marq',
  'marcc',

  // ==========================================
  // 2. HOKSEN / HOXEN VARIATIONS (35+ items)
  // ==========================================
  'hoksen',
  'hoxen',
  'hoxsen',
  'hoxon',
  'hoxson',
  'hoxxen',
  'hokson',
  'hooksen',
  'hooxen',
  'hooxson',
  'hocks',
  'hocksen',
  'hockson',
  'hokks',
  'hokksen',
  'hokkson',
  'hogsen',
  'hogson',
  'hokzen',
  'hokzon',
  'hoxzen',
  'hoxzon',
  'hoeksen',
  'hoegsen',
  'hoks',
  'hokkz',
  'h0ksen',
  'h0xen',
  'h0cksen',
  'h0x0n',
  'h0xsen',
  'hox',
  'hoxx',
  'hoxxn',
  'hocksun',

  // ==========================================
  // 3. COMBINED MARKO + HOKSEN VARIANTS (40+ items)
  // ==========================================
  'markohoksen',
  'markohoxen',
  'marcohoksen',
  'marcohoxen',
  'marckohoksen',
  'marckohoxen',
  'markko_hoksen',
  'marko_hoksen',
  'marco_hoksen',
  'marko_hoxen',
  'marco_hoxen',
  'marko-hoksen',
  'marco-hoksen',
  'marko-hoxen',
  'marco-hoxen',
  'markohocks',
  'marcohocks',
  'markohocksen',
  'marcohocksen',
  'markohokson',
  'marcohokson',
  'markohoeksen',
  'marcohoeksen',
  'marko_h',
  'marco_h',
  'm_hoksen',
  'm_hoxen',
  'm_hocksen',
  'mhoksen',
  'mhoxen',
  'mhocksen',
  'hoksenmarko',
  'hoxenmarko',
  'hocksenmarko',
  'hoksen_marko',
  'hoxen_marko',
  'hoksenmarco',
  'hoxenmarco',
  'hoksen_marco',
  'markohoksn',
  'marcohoksn',

  // ==========================================
  // 4. JONATECH & JONATEK VARIATIONS (40+ items)
  // ==========================================
  'jonatech',
  'jonatek',
  'jonathech',
  'jonatec',
  'jonathck',
  'jonattech',
  'jonattec',
  'jonattek',
  'jonnatech',
  'jonnatek',
  'johnatech',
  'johnatek',
  'jonah-tech',
  'jona-tech',
  'jona-tek',
  'yonatech',
  'yonatek',
  'jonatechhq',
  'jonatechofficial',
  'jonatechadmin',
  'jonatech_admin',
  'jonatech_official',
  'jonatech_dev',
  'jonatech_staff',
  'jonatech_team',
  'jonatech_support',
  'jonatech_owner',
  'jonatech_system',
  'jonatech_bot',
  'jonatech_mod',
  'jonatech_moderator',
  'jonatech_security',
  'jonatech_net',
  'jonatech_app',
  'jonatech_chat',
  'jonatechnology',
  'jona_technologies',
  'jonatech_cloud',
  'j0natech',
  'j0n@tech',
  'j0natek',
  'j0n@tek',

  // ==========================================
  // 5. OFFICIAL & ADMIN IMPERSONATION COMBOS (30+ items)
  // ==========================================
  'marko_admin',
  'admin_marko',
  'marko_official',
  'official_marko',
  'real_marko',
  'marko_real',
  'marko_dev',
  'marko_ceo',
  'marko_owner',
  'marko_founder',
  'marko_staff',
  'marko_system',
  'marko_mod',
  'mr_marko',
  'mrmarko',
  'master_marko',
  'mastermarko',
  'hoksen_official',
  'hoksen_admin',
  'hoksen_dev',
  'mr_hoksen',
  'mrhoksen',
  'hoksen_real',
  'official_markohoksen',
  'real_markohoksen',
  'markohoksen_admin',
  'markohoksen_dev',
  'markohoksen_official',
  'markohoksen_founder',
  'markohoksen_ceo'
];
